# Disable the newline at the start of the prompt
add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10



[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[time]
disabled = false
format = "[$time]($style)"

[directory]
style = "bold 90"
truncation_length = 0
truncate_to_repo = false

[dotnet]
symbol = "ğŸ¥… "
style = "green"
heuristic = false

[env_var]
disabled = false

[git_branch]
style = "170"
symbol = "î—»:îœ¥"
truncation_length = 7
truncation_symbol = ""

[git_commit]
disabled = false
commit_hash_length = 4



[git_status]
conflicted = "ğŸ³ "
ahead = "ğŸ ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
modified = "ğŸ“"
staged='[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "

[hostname]
ssh_only = false
prefix = "âŸª"
suffix = "âŸ«âŸ«âŸ«"
trim_at = ".companyname.com"
format = "[$hostname]($style) "
disabled = true

[jobs]
symbol = "+ "
threshold = 4



[nodejs]
style = "211"

[ruby]
symbol = "îˆ¾ "
style = "211"

[package]
style = "211"
symbol = "ï£– "

[python]
disabled = false
symbol = "ğŸ‘¾ "
pyenv_version_name = true
style = "35"